# Hyprland Layer Shell Configuration for QuickShell

# Regras de Layer (Popups e Notificações)
layerrule = animation popin, ^(quickshell)$
layerrule = blur, ^(quickshell)$
layerrule = ignorealpha 0.3, ^(quickshell)$

# Definição de Animação
bezier = myBezier, 0.05, 0.9, 0.1, 1.05
animation = windows, 1, 7, myBezier

# Regras de Janela (Window Rules V2)
windowrulev2 = float, class:^(quickshell)$
windowrulev2 = noblur, class:^(quickshell)$, title:^(quickshell)$
